### ISSUE TITLE
Transaction direction values are hidden behind internal package

### ISSUE THREAD

**Issue by sudotliu** [Modern-Treasury/modern-treasury-go#120]
The recent changes to consolidate transaction entry directions are great although it seems to have left things in a peculiar state as far as usage goes. There is a `shared.TransactionDirection` type that is aliased into a `moderntreasury.TransactionDirection` type but the actual enum values are not exposed and cannot be referenced directly from the `shared` package since that is an internal package.

This means that we cannot easily specify this type without clunky type-casting calls like `mt.F(moderntreasury.TransactionDirection("debit")),` or wrapping the aliased type with our own constant like so:
```go
// Wrappers for Modern Treasury transaction entry directions
const (
	Debit  moderntreasury.TransactionDirection = "debit"
	Credit moderntreasury.TransactionDirection = "credit"
)
```

As an SDK consumer, I would have expected something like exported values somewhere such that we can reference something like `moderntreasury.Debit` and `moderntreasury.Credit` or something much closer to that.

Is this something that can be added or are there particular reasons for this design that I'm missing?

**Comment by rattrayalex** [comment]
Hi @sudotliu ! Thanks so much for reporting this, sorry for the inconvenience. We should definitely be exporting the aliases for the enum values as well, that's a mistake. We'll get that out soon.

**Comment by sudotliu** [comment]
Thanks @rattrayalex ! Please let me know when you have an ETA on this so we can keep an eye out for the update, thank you!

**Comment by rattrayalex** [comment]
Hi @sudotliu , [this was released](https://github.com/Modern-Treasury/modern-treasury-go/pull/117/files#diff-cdfb14ab9436d488090578aa941145e091a6264c28e752a27f446568f7f779c1R600-R603) yesterday in v2.1.0!
