### ISSUE TITLE
Request config not properly handling errors

### ISSUE THREAD

**Issue by LeroyChen96** [Modern-Treasury/modern-treasury-go#77]
https://github.com/Modern-Treasury/modern-treasury-go/blob/71cb4608ba9ee66161e540332a071fcbcb8f9aff/internal/requestconfig/requestconfig.go#L189-L197

There is a bug here that the error on line 190 is not properly checked. In the case of context timeout/cancel, it is possible that `res` is nil and has no headers, which will panic on line 197.

Attaching a screenshot below of debugger state highlighting this issue, and the relevant code block:
![image](https://github.com/Modern-Treasury/modern-treasury-go/assets/28577511/0ee2d320-b63a-4ad5-80e5-eea32792b5f9)
```
t.Run("context error will fail to request client", func(t *testing.T) {
	cancelCtx, cancel := context.WithCancel(context.Background())
	cancel()
	client.Ping(cancelCtx) // this panics instead of returning error
})
```

**Comment by rattrayalex** [comment]
The fix for this will be released in 1.4.1: https://github.com/Modern-Treasury/modern-treasury-go/pull/79
